version: '3.9'

services:
  api:
    build: .
    ports:
      - '8080:3005'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.3-alpine
    ports:
      - '5400:5432'
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bank

  redis:
    image: redis:6.2-alpine
    ports:
      - '6300:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30
